apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus.yaml
- argo-rollouts.yaml
- cert-manager.yaml
- github.com/audryus/gitops-argo/istio/overlays/oci
- grafana.yaml
- jaeger.yaml
- kiali.yaml
- gateway-api.yaml
- ubiquitous-spoon.yaml
- bookish-memory.yaml