apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- projects.yaml
- sealed-secrets.yaml
- prometheus.yaml
- metrics-server.yaml
#- argo-workflows.yaml
#- argo-events.yaml
#- istio.yaml
