apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- projects.yaml
#- sealed-secrets.yaml
- prometheus.yaml
- metrics-server.yaml
- github.com/audryus/gitops-argo/istio
#- elastic-eck.yaml
- k6-operator.yaml
- gocd.yaml
#- argo-workflows.yaml
#- argo-events.yaml
