apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-app
  namespace: silly-app
  labels:
    app: silly-app
spec:
  selector:
    matchLabels:
      app: silly-app
  template:
    metadata:
      labels:
        app: silly-app
    spec:
      containers:
      - name: silly-app
        image: audryus/silly-app:1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi