apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- traefik-mdw-redirecttohttps.yaml
- traefik-mdw-stripprefix.yaml
- cert.yaml
- ingress.yaml
namespace: silly-app